# -*- coding: utf-8 -*-
"""DMA_CP_w2v_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11M8Cg1KD7WQVdUbDY8DJZ3nbWgmRzL4U
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
# %pylab inline
from textblob import TextBlob

train = pd.read_excel('/content/drive/My Drive/Constraint_English_Train.xlsx')
val = pd.read_excel("/content/drive/My Drive/Constraint_English_Val.xlsx")
test_df = pd.read_excel("/content/drive/My Drive/Constraint_English_Test.xlsx") #TEST DATA -->> test_df
train_df = pd.concat([train,val],ignore_index=True) # TRAIN DATA -->> train_df
train_df['label'] = train_df['label'].replace(['fake','real'],[0,1])

X = train_df['tweet']
y = train_df['label']

import re
import string

def remove_pattern(input_txt,pattern):
    r=re.findall(pattern,input_txt)
    for i in r:
        input_txt=re.sub(i, '', input_txt)
    return input_txt

#remove twitter handles
train_df['tweet']=np.vectorize(remove_pattern)(train_df['tweet'], "@[\w]*")
test_df['tweet']=np.vectorize(remove_pattern)(test_df['tweet'], "@[\w]*")

#remove urls
train_df['tweet']=train_df['tweet'].str.replace('http\S+|www.\S+', '', case=False)
test_df['tweet']=test_df['tweet'].str.replace('http\S+|www.\S+', '', case=False)


#remove puctuations, numbers, and special characters
train_df['tweet']=train_df['tweet'].str.replace('[^A-Za-z]+', ' ')
test_df['tweet']=test_df['tweet'].str.replace('[^A-Za-z]+', ' ')
train_df['tweet'].head(10)

#lowercase
train_df['tweet'] = train_df['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
test_df['tweet'] = test_df['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
train_df['tweet'].head(10)

import nltk
nltk.download('stopwords')

#remove stopwords

import nltk
from nltk.corpus import stopwords
stop = stopwords.words('english')
train_df['tweet'] = train_df['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
train_df['tweet'].head()
test_df['tweet'] = test_df['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
test_df['tweet'].head()

nltk.download('wordnet')

#lemmatisation
from textblob import Word
train_df['tweet'] = train_df['tweet'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
test_df['tweet'] = test_df['tweet'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))

test_df['tweet'].head()

X_final = train_df['tweet']
y_final = train_df['label']

from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(X_final, y_final, test_size=0.25, shuffle=False)

x_test = test_df['tweet']

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_val = encoder.fit_transform(y_val)

y_train
y_val

from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(x_train)

X_train = tokenizer.texts_to_sequences(x_train)
X_val = tokenizer.texts_to_sequences(x_val)
X_test = tokenizer.texts_to_sequences(x_test)

vocab_size = len(tokenizer.word_index) + 1  # Adding 1 because of reserved 0 index

print(x_train[2])
print(X_train[2])

from keras.preprocessing.sequence import pad_sequences

maxlen = 100

X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_val = pad_sequences(X_val, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

print(X_test[0, :])

'''from keras.models import Sequential
from keras import layers
from keras.layers import Dropout
from keras.optimizers import Adam as adamm
from keras.optimizers import RMSprop as rms
embedding_dim = 50


model = Sequential()
model.add(layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=maxlen))
model.add(layers.GlobalMaxPool1D())
model.add(layers.Dense(100,activation='relu' ))
model.add(Dropout(0.3))
model.add(layers.Dense(100, activation='relu'))
model.add(Dropout(0.3))
model.add(layers.Dense(1, activation='sigmoid'))
optimizer = adamm(lr=0.0001)#0.07 or 0.075 without dropout
#optimizer = rms(learning_rate=0.001)
model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
model.summary()'''

from keras.models import Sequential
from keras import layers
from keras.layers import Dropout,Bidirectional,LSTM
from keras.optimizers import Adam as adamm
from keras.optimizers import RMSprop as rms
embedding_dim = 50


model = Sequential()
model.add(layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=maxlen))
Bidirectional(LSTM(100, return_sequences=True))
model.add(Dropout(0.3))
model.add(layers.GlobalMaxPool1D())
model.add(layers.Dense(100,activation='relu' ))
model.add(Dropout(0.3))
model.add(layers.Dense(100, activation='relu'))
model.add(Dropout(0.3))
model.add(layers.Dense(1, activation='sigmoid'))
optimizer = adamm(lr=0.0001)#0.07 or 0.075 without dropout
#optimizer = rms(learning_rate=0.001)
model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

#model.fit(X_train, y_train, epochs=20, validation_data=(X_val, y_val), batch_size=10)
#model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val), batch_size=40)#94/ 86
#model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), batch_size=1000)##95/90

#model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), batch_size=1070)
history = model.fit(X_train, y_train, epochs=45, validation_data=(X_val, y_val), batch_size=1070)

print(history.history['loss'])
print(history.history['accuracy'])
print(history.history['val_loss'])
print(history.history['val_accuracy'])

figsize(8,8)
pyplot.plot(history.history['loss'])
pyplot.plot(history.history['val_loss'])
pyplot.title('model train vs validation loss')
pyplot.ylabel('loss')
pyplot.xlabel('epoch')
pyplot.legend(['train', 'validation'], loc='upper right')
pyplot.show()

figsize(8,8)
pyplot.plot(history.history['accuracy'])
pyplot.plot(history.history['val_accuracy'])
pyplot.title('model train vs validation accuracy')
pyplot.ylabel('loss')
pyplot.xlabel('epoch')
pyplot.legend(['train', 'validation'], loc='upper right')
pyplot.show()

loss, accuracy = model.evaluate(X_train, y_train, verbose=False)
print("Training Accuracy: {:.2f}".format(accuracy))
loss, accuracy = model.evaluate(X_val, y_val, verbose=False)
print("Testing Accuracy:  {:.2f}".format(accuracy))

predictions = model.predict_classes(X_val)

from sklearn.metrics import f1_score,recall_score,precision_score
print("precision: ",precision_score(y_val, predictions,average='weighted'))
print("recall:   ",recall_score(y_val, predictions, average='weighted'))
print("f1 score: ",f1_score(y_val, predictions,average='weighted'))

'''prediction_test = model.predict_classes(X_test)
id = list(range(1, 2141))
list_tuple = list(zip(id,prediction_test))

#Creating a Dataframe with id and predited labels
prediction_test = pd.DataFrame(list_tuple, columns = ['id','label'])

#Converting 1s to real and 0s to fake
prediction_test['label'] = prediction_test['label'].replace([0,1],['fake','real'])

#Saving the document in .txt file
prediction_test.to_csv("/content/drive/My Drive/DMA CP/answerCNNmodelPart4.txt",header = True, sep = ",",index = False)'''