# -*- coding: utf-8 -*-
"""5DMACP06_5E_11_Covid19FakeNewsDetectionEnglish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWHklx1w7B0z9URfsG6XFIiN5AwYSkgP
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

!pip install transformers==3.3.1

"""**Reading the Data**  
We read the input train file which has the columns id,tweet and label. Then the column 'id' is dropped and we assigned numerical code '0' and '1' to the categorical labels 'fake' and 'real' respectively.
"""

import pandas as pd
import numpy as np
train = pd.read_csv('/content/drive/My Drive/Constraint_English_Train - Sheet1.csv',
                 header=None,names=['id','tweet','label'])
train = train.drop(columns='id')
train= train[1:]
train.label = train.label.apply({'fake':0,'real':1}.get)
train.head(10)

test=pd.read_csv('/content/drive/My Drive/DMA CP/english_test_with_labels - Sheet1.csv')
test.label = test.label.apply({'fake':0,'real':1}.get)
test

val = pd.read_csv('/content/drive/My Drive/DMA CP/Constraint_English_Test - Sheet1.csv')
val = val.drop(columns='id')
#val = val[1:]
val['label']=test['label']
val

"""**Tokenize the input text**"""

import pandas as pd
from torch.utils.data import Dataset,DataLoader

class Dataset(Dataset):
  def __init__(self,text,label,tokenizer,max_len):
    self.text = text
    self.label = label
    self.tokenizer = tokenizer
    self.max_len = max_len

  def __len__(self):
    return len(self.text)

  def __getitem__(self,item):
    text = str(self.text[item])
    label = self.label[item]

    encoding = self.tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length = self.max_len,
        return_token_type_ids = False,
        padding = 'max_length',
        return_attention_mask= True,
        return_tensors='pt',
        truncation=True
    )

    return {
        'text' : text,
        'input_ids' : encoding['input_ids'].flatten(),
        'attention_mask' : encoding['attention_mask'].flatten(),
        'label' : torch.tensor(label,dtype=torch.long)

    }

print('Training set size:',train.shape)
#Uncomment the next line when we have the test data
#print('Testing set size:',test.shape)
print('validation set size:',val.shape)

"""**Function to load the tokenized data**"""

def create_data_loader(df,tokenizer,max_len,batch_size):
  ds = Dataset(
      text = df.tweet.to_numpy(),
      label = df.label.to_numpy(),
      tokenizer = tokenizer,
      max_len = max_len
  )

  return DataLoader(ds,
                    batch_size = batch_size,
                    shuffle = True,
                    num_workers=4)

from transformers import XLNetTokenizer,XLNetModel,AdamW,get_linear_schedule_with_warmup,AutoModel,AutoTokenizer
device = 'cuda'
PRE_TRAINED_MODEL_NAME = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME)

"""**Data Loading**

Tokenized train and validation data are loaded which have batch size 32 and maximum length of 128 for padding.
"""

BATCH_SIZE = 32
MAX_LEN = 128
train_data_loader = create_data_loader(train,tokenizer,MAX_LEN,BATCH_SIZE)
val_data_loader = create_data_loader(val,tokenizer,MAX_LEN,BATCH_SIZE)

BERT_model = AutoModel.from_pretrained(PRE_TRAINED_MODEL_NAME)

"""**Architecture of Classifier model**   """

import torch.nn as nn
class Classifier(nn.Module):
  def __init__(self, n_classes):
    super(Classifier, self).__init__()
    self.auto = AutoModel.from_pretrained('bert-base-uncased')
    self.drop = nn.Dropout(p=0.4)
    #self.out = nn.Linear(self.bert.config.hidden_size, n_classes)
    self.out1 = nn.Linear(self.auto.config.hidden_size, 128)
    self.drop1 = nn.Dropout(p=0.4)
    self.relu = nn.ReLU()
    self.out = nn.Linear(128, n_classes)

  def forward(self, input_ids, attention_mask):
    _,pooled_output = self.auto(
      input_ids=input_ids,
      attention_mask=attention_mask
    )
    #output = self.relu(pooled_output)
    output = self.drop(pooled_output)
    output = self.out1(output)
    output = self.relu(output)
    output = self.drop1(output)
    return self.out(output)

model = Classifier(2)
model = model.to(device)

"""**Parameter initialization**"""

EPOCHS = 10
optimizer = AdamW(model.parameters(), lr=0.00002, correct_bias=False)
total_steps = len(train_data_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
  optimizer,
  num_warmup_steps=0,
  num_training_steps=total_steps
)

loss_fn = nn.CrossEntropyLoss().to(device)

"""**Funtion to train the model**"""

def train_epoch(model,data_loader,loss_fn,optimizer,device,scheduler,n_examples):
    model = model.train()
    losses = []
    correct_predictions = 0

    for data in data_loader:
        input_ids = data['input_ids'].to(device)
        attention_mask = data['attention_mask'].to(device)
        labels = data['label'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
            )
        _, preds = torch.max(outputs, dim=1)
        loss = loss_fn(outputs,labels)

        correct_predictions += torch.sum(preds == labels)
        losses.append(loss.item())

        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

    return correct_predictions.double() / n_examples, np.mean(losses)

"""**Funtion to evaluate the model**"""

def eval_model(model, data_loader, loss_fn, device, n_examples):
  model = model.eval()
  losses = []
  correct_predictions = 0
  with torch.no_grad():
    for d in data_loader:
      input_ids = d["input_ids"].to(device)
      attention_mask = d["attention_mask"].to(device)
      labels = d["label"].to(device)
      outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
      )
      _, preds = torch.max(outputs, dim=1)
      loss = loss_fn(outputs, labels)
      correct_predictions += torch.sum(preds == labels)
      losses.append(loss.item())
  return correct_predictions.double() / n_examples, np.mean(losses)

import time

def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

"""**Training the model**"""

from collections import defaultdict
import torch

history = defaultdict(list)
best_accuracy = 0
for epoch in range(EPOCHS):


  start_time = time.time()
  train_acc,train_loss = train_epoch(
      model,
      train_data_loader,
      loss_fn,
      optimizer,
      device,
      scheduler,
      len(train)
  )


  val_acc,val_loss = eval_model(
      model,
      val_data_loader,
      loss_fn,
      device,
      len(val)
  )

  end_time = time.time()
  epoch_mins, epoch_secs = epoch_time(start_time, end_time)
  print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
  print(f'Train Loss {train_loss} accuracy {train_acc}')
  print(f'Val Loss {val_loss} accuracy {val_acc}')
  print()

  history['train_acc'].append(train_acc)
  history['train_loss'].append(train_loss)
  history['val_acc'].append(val_acc)
  history['val_loss'].append(val_loss)

  if val_acc > best_accuracy:
    torch.save(model.state_dict(),'bert-base-uncased.bin')
    best_accuracy = val_acc

"""**Model Evaluation**  
Bias variance tradeoff
"""

import matplotlib.pyplot as plt
plt.plot(history['train_acc'], label='train accuracy')
plt.plot(history['val_acc'], label='validation accuracy')
plt.title('Training history')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.ylim([0, 1])

plt.plot(history['train_loss'], label='train loss')
plt.plot(history['val_loss'], label='validation loss')
plt.title('Training history')
plt.ylabel('loss')
plt.xlabel('Epoch')
plt.legend()
plt.ylim(0,1)

val_acc, _ = eval_model(
  model,
  val_data_loader,
  loss_fn,
  device,
  len(val)
)
val_acc.item()

"""**Function to get the label for the test data**"""

def get_predictions(model, data_loader):
  model = model.eval()
  sentence = []
  predictions = []
  prediction_probs = []
  real_values = []
  with torch.no_grad():
    for d in data_loader:
      texts = d["text"]
      input_ids = d["input_ids"].to(device)
      attention_mask = d["attention_mask"].to(device)
      labels = d["label"].to(device)
      outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
      )
      _, preds = torch.max(outputs, dim=1)
      sentence.extend(texts)
      predictions.extend(preds)
      prediction_probs.extend(outputs)
      real_values.extend(labels)
  predictions = torch.stack(predictions).cpu()
  prediction_probs = torch.stack(prediction_probs).cpu()
  real_values = torch.stack(real_values).cpu()
  return sentence, predictions, prediction_probs, real_values

y_review_texts, y_pred, y_pred_probs, y_test = get_predictions(
  model,
  val_data_loader
)

class_name = ['fake','real']

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test, y_pred, target_names=class_name,zero_division=0))

from sklearn.metrics import f1_score,recall_score,precision_score
print("precision: ",precision_score(y_test, y_pred))
print("recall:   ",recall_score(y_test, y_pred))
print("f1 score: ",f1_score(y_test, y_pred))

"""**Confusion Matrix**"""

import seaborn as sns
def show_confusion_matrix(confusion_matrix):
  hmap = sns.heatmap(confusion_matrix, annot=True, fmt="d", cmap="Blues")
  hmap.yaxis.set_ticklabels(hmap.yaxis.get_ticklabels(), rotation=0, ha='right')
  hmap.xaxis.set_ticklabels(hmap.xaxis.get_ticklabels(), rotation=30, ha='right')
  plt.ylabel('True sentiment')
  plt.xlabel('Predicted sentiment');
cm = confusion_matrix(y_test, y_pred)
df_cm = pd.DataFrame(cm, index=class_name, columns=class_name)
show_confusion_matrix(df_cm)

'''prediction_test = y_pred
id = list(range(1, 2141))
list_tuple = list(zip(id,prediction_test))

#Creating a Dataframe with id and predited labels
prediction_test = pd.DataFrame(list_tuple, columns = ['id','label'])

#Converting 1s to real and 0s to fake
prediction_test['label'] = prediction_test['label'].replace([0,1],['fake','real'])

#Saving the document in .txt file
prediction_test.to_csv("/content/drive/My Drive/DMA CP/answerBERT.txt",header = True, sep = ",",index = False)'''

"""**References**  
[1]Wani, Apurva, Isha Joshi, Snehal Khandve, Vedangi Wagh, and Raviraj Joshi. "Evaluating Deep Learning Approaches for Covid19 Fake News Detection." arXiv preprint arXiv:2101.04012 (2021).  
[2]https://www.analyticsvidhya.com/blog/2020/07/transfer-learning-for-nlp-fine-tuning-bert-for-text-classification/
"""

